//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekz.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int IdEmployee { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> Bday { get; set; }
        public string Pasport { get; set; }
        public string BankInfo { get; set; }
        public Nullable<int> IdFam { get; set; }
        public Nullable<int> IdHealf { get; set; }
    
        public virtual Fam Fam { get; set; }
        public virtual Healf Healf { get; set; }
        public virtual User User { get; set; }
    }
}
