//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekz.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.ProductMater = new HashSet<ProductMater>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdType { get; set; }
        public string Name { get; set; }
        public Nullable<int> KolvoUpak { get; set; }
        public Nullable<int> IdEd { get; set; }
        public Nullable<decimal> CostEd { get; set; }
        public Nullable<int> MinKol { get; set; }
        public Nullable<int> Kol { get; set; }
        public Nullable<int> KolOnSclad { get; set; }
    
        public virtual EdIzmer EdIzmer { get; set; }
        public virtual Type Type { get; set; }
        public virtual ICollection<ProductMater> ProductMater { get; set; }
    }
}
