//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekz.Conn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DecorEntities : DbContext
    {
        public DecorEntities()
            : base("name=DecorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EdIzmer> EdIzmer { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Fam> Fam { get; set; }
        public DbSet<Healf> Healf { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductMater> ProductMater { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Type> Type { get; set; }
        public DbSet<TypeProd> TypeProd { get; set; }
        public DbSet<User> User { get; set; }
    }
}
