//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekz.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMater
    {
        public int Id { get; set; }
        public Nullable<int> IdProd { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public Nullable<decimal> Kolva { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
