//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekz.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Art { get; set; }
        public Nullable<int> IdType { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> MinCostPart { get; set; }
        public Nullable<decimal> Weigh { get; set; }
    
        public virtual TypeProd TypeProd { get; set; }
    }
}
